#ifndef STANDALONE_APPCONFIGURATION_H
#define STANDALONE_APPCONFIGURATION_H

#define APP_NAME "Standalone"
#define APP_CODE "standalone"
#define APP_VERSION "PRE-ALPHA 0.0.0"

#endif //STANDALONE_APPCONFIGURATION_H
