"Ability"
{
    "Military_Ammo"
    {
        "Max_Level"                     "6"
        "Levels"
        {
            "1"                         "1"
            "2"                         "3"
            "3"                         "5"
            "4"                         "7"
            "5"                         "36"
            "6"                         "41"
        }

        "Values"
        {
            "Bonus_Damage"              "10 25 40 60 100 150"
        }
    }
}
