"Addon_Info"
{
    "Name"                              "Addon Info Example"
    "Game_Modes"
    {
        "Default"
        {
            "Teams"
            {
                "Angels"                "5"
                "Demons"                "5"
            }
            "Map"                       "default"
            "Respect_Party"             "True" // Optional to false
            "Script_File"               "Addon.lua"
        }
    }
}