"Ability"
{
    "Memento_Mori"
    {
        "Script_File"                   "Ability/Hero/Mori/Memento_Mori.lua"
        "Max_Levels"                    "3"

        "Ability_Type"                  "Ultimate"

        "Values"
        {
            "Respawn_Time_Percentage"   "75"

            "Ghost_Movement_Speed"      "100 200 300"
            "Ghost_Vision_Day"          "800 1000 1200"
            "Ghost_Vision_Night"        "800 1000 1200"
        }
    }
}
