-- Damage Type
DAMAGE_PURE = 0
DAMAGE_PHYSICAL = 1
DAMAGE_MAGICAL = 2

-- Attribute
ATTRIBUTE_STRENGTH = 0
ATTRIBUTE_AGILITY = 1
ATTRIBUTE_INTELLIGENCE = 2
ATTRIBUTE_CHARISMA = 3

-- Teams
TEAM_NEUTRAL = 0
TEAM_ANGELS = 1
TEAM_DEMONS = 2
TEAM_1 = TEAM_ANGELS
TEAM_2 = TEAM_DEMONS
TEAM_3 = 3
TEAM_4 = 4
TEAM_5 = 5
TEAM_6 = 6
TEAM_7 = 7
TEAM_8 = 8
TEAM_9 = 9
TEAM_10 = 10
TEAM_11 = 11
TEAM_12 = 12
TEAM_13 = 13
TEAM_14 = 14
TEAM_15 = 15

-- Team Filter
TEAM_FILTER_ANY = 0
TEAM_FILTER_NEUTRAL = 1
TEAM_FILTER_ANGELS = 2
TEAM_FILTER_DEMONS = 4
TEAM_FILTER_1 = TEAM_FILTER_ANGELS
TEAM_FILTER_2 = TEAM_FILTER_DEMONS
TEAM_FILTER_3 = 8
TEAM_FILTER_4 = 16
TEAM_FILTER_5 = 32
TEAM_FILTER_6 = 64
TEAM_FILTER_7 = 128
TEAM_FILTER_8 = 256
TEAM_FILTER_9 = 512
TEAM_FILTER_10 = 1024
TEAM_FILTER_11 = 2048
TEAM_FILTER_12 = 4096
TEAM_FILTER_13 = 8192
TEAM_FILTER_14 = 16384
TEAM_FILTER_15 = 32768

-- Purge Type
URGE_NONE = 0
PURGE_SOFT = 1
PURGE_HARD = 2
PURGE_RESPAWN = 3 --Some modifiers may not want to be purged but want to disappear on death

-- Type Filter

-- Flag Filter

-- Find Order
FIND_ORDER_ANY = 0
FIND_ORDER_CLOSEST = 1
FIND_ORDER_FARTHEST = 2
FIND_ORDER_RANDOMIZED = 3

-- Modifier Priority
MODIFIER_PRIORITY_MINIMAL     = -3
MODIFIER_PRIORITY_LOWEST      = -2
MODIFIER_PRIORITY_LOW         = -1
MODIFIER_PRIORITY_NORMAL      = 0 -- Normal, should be default value
MODIFIER_PRIORITY_HIGH        = 1
MODIFIER_PRIORITY_ULTRA       = 2
MODIFIER_PRIORITY_SUPER_ULTRA = 3

